# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: OpenInfra Days Korea 2018
email: master@openinfradays.kr
description: OpenInfra Days Korea 2018
baseurl: "/2018" # the subpath of your site, e.g. /blog
url: "https://openstack-kr.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Usernames and API Keys
github_username: openstack-kr
gmaps_embed_api_key: AIzaSyB94qSWPswDXOjd35pfzUpQduKzjJvPiRs

# Location & time
period: "2018년 6월 28-29일 오전 9:00 ~ 오후 6:00"
location: "COEX 3층 컨퍼런스룸E (구 Hall E)"
address: "서울특별시 강남구 봉은사로 524"
location_query: "코엑스"

# Event Sponsors
hosts:
  - name: OpenStack 한국 커뮤니티
    image: nipa.png
    url: https://www.openstack.or.kr
    desc: >
      -
  - name: OpenStack Foundation
    image: nipa.png
    url: https://www.openstack.org
    desc: >
      -
  - name: CNCF 한국 커뮤니티
    image: nipa.png
    url: https://www.openstack.or.kr
    desc: >
      -
runs:
  - name: OpenStack 한국 커뮤니티
    image: nipa.png
    url: https://www.openstack.or.kr
    desc: >
      -
  - name: OpenStack Foundation
    image: nipa.png
    url: https://www.openstack.org
    desc: >
      -
  - name: 한국정보통신산업진흥원
    image: nipa.png
    url: https://www.nipa.kr
    desc: >
      -
platinums:
  - name: NetApp
    image: nipa.png
    url: https://www.nipa.kr
    desc: >
      -
  - name: SK Telecom
    image: nipa.png
    url: https://www.nipa.kr
    desc: >
      -
  - name: 맨텍
    image: nipa.png
    url: https://www.nipa.kr
    desc: >
      -
  - name: 오픈소스컨설팅
    image: nipa.png
    url: https://www.nipa.kr
    desc: >
      -
  - name: 삼성전자
    image: nipa.png
    url: https://www.nipa.kr
    desc: >
      -
  - name: Cloud Native Foundation
    image: nipa.png
    url: https://www.openstack.org
    desc: >
      -
golds:
  - name: SUSE
    image: nipa.png
    url: https://www.nipa.kr
    desc: >
      -
  - name: HP Enterprise
    image: nipa.png
    url: https://www.nipa.kr
    desc: >
      -
  - name: MTOS
    image: nipa.png
    url: https://www.nipa.kr
    desc: >
      -
  - name: Nokia
    image: nipa.png
    url: https://www.nipa.kr
    desc: >
      -
  - name: SPTek
    image: nipa.png
    url: https://www.nipa.kr
    desc: >
      -
  - name: ATTO Research
    image: nipa.png
    url: https://www.nipa.kr
    desc: >
      -
  - name: KINX
    image: nipa.png
    url: https://www.nipa.kr
    desc: >
      -
silvers:
  - name: OpenStack Foundation
    image: nipa.png
    url: https://www.openstack.org
    desc: >
      -
  - name: Innogrid & Westpak
    image: nipa.png
    url: https://www.openstack.org
    desc: >
      -
  - name: LINE
    image: nipa.png
    url: https://www.openstack.org
    desc: >
      -
  - name: XS Lab.
    image: nipa.png
    url: https://www.openstack.org
    desc: >
      -
  - name: Edenchain
    image: nipa.png
    url: https://www.openstack.org
    desc: >
      -
sponsors:
  - name: CUBRID
    image: microsoft.svg
    url: https://www.microsoft.com/ko-kr
    desc: >
      (네임택 후원)
  - name: NCloud24
    image: microsoft.svg
    url: https://www.microsoft.com/ko-kr
    desc: >
      (실습 VM 후원)
  - name: Cafe24
    image: microsoft.svg
    url: https://www.microsoft.com/ko-kr
    desc: >
      (실습 VM 후원)

# license
owner: "MeltingCon Community Alliance"
code_license: "MIT"
copyright: Copyright (c) 2018 OpenStack Korea Community All Rights Reserved.
content_license: "CC BY-SA 4.0"

# Custom Collection
collections:
  sessions:
    title: Sessions
    output: true
    permalink: "/session/:path"

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
  - jekyll-paginate
exclude:
  - Gemfile
  - Gemfile.lock
